b3e33c27add19193791ed2e5e9b78444

In [48]:
import json
import requests
import csv

In [49]:
# API credentials
API_KEY = "b3e33c27add19193791ed2e5e9b78444"
CITY = "London"
lat=[]
lon=[]
state_code=[]
country_code=[]
limit=5
cnt=240 #240 hours
#url = f"http://api.openweathermap.org/data/2.5/forecast/daily?lat={lat}&lon={lon}&cnt={cnt}&appid={API_KEY}"
url = f"http://api.openweathermap.org/data/2.5/forecast?q={CITY}&cnt={cnt}&appid={API_KEY}"
#url=f"http://api.openweathermap.org/geo/1.0/direct?q={CITY},{state_code},{country_code}&limit={limit}&appid={API_KEY}"

response=requests.get(url)
print(response)

<Response [200]>

In [50]:
baseurl='http://api.openweathermap.org/data/2.5/forecast?q='
endpoint=f'{CITY}&cnt={cnt}&appid={API_KEY}'

FETCH DATA(EXTRACT)

In [51]:
def main_request(baseurl,endpoint):
    url=f"{baseurl}{endpoint}"
    r=requests.get(url)
    return r.json()

In [52]:
if response.status_code==200:
    data = main_request(baseurl,endpoint)
    print(data) #PRINTS ALL CONTENT

else:
    print(f"Failed to retrieve data. Status code: {response.status_code}")

{'cod': '200', 'message': 0, 'cnt': 40, 'list': [{'dt': 1750582800, 'main': {'temp': 294.01, 'feels_like': 293.9, 'temp_min': 293.98, 'temp_max': 294.01, 'pressure': 1014, 'sea_level': 1014, 'grnd_level': 1010, 'humidity': 67, 'temp_kf': 0.03}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 13}, 'wind': {'speed': 5.67, 'deg': 248, 'gust': 8.67}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-22 09:00:00'}, {'dt': 1750593600, 'main': {'temp': 294.92, 'feels_like': 294.67, 'temp_min': 294.92, 'temp_max': 296.75, 'pressure': 1014, 'sea_level': 1014, 'grnd_level': 1009, 'humidity': 58, 'temp_kf': -1.83}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 16}, 'wind': {'speed': 6.79, 'deg': 239, 'gust': 10.62}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-22 12:00:00'}, {'dt': 1750604400, 'main': {'temp': 293.78, 'feels_like': 293.23, 'temp_min': 293.66, 'temp_max': 293.78, 'pressure': 1013, 'sea_level': 1013, 'grnd_level': 1008, 'humidity': 51, 'temp_kf': 0.12}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 71}, 'wind': {'speed': 7.54, 'deg': 229, 'gust': 11.01}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-22 15:00:00'}, {'dt': 1750615200, 'main': {'temp': 294.06, 'feels_like': 293.67, 'temp_min': 294.06, 'temp_max': 294.06, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1007, 'humidity': 56, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 5.79, 'deg': 251, 'gust': 10.58}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-22 18:00:00'}, {'dt': 1750626000, 'main': {'temp': 289.43, 'feels_like': 288.78, 'temp_min': 289.43, 'temp_max': 289.43, 'pressure': 1012, 'sea_level': 1012, 'grnd_level': 1008, 'humidity': 64, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 72}, 'wind': {'speed': 4.59, 'deg': 255, 'gust': 11.44}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-06-22 21:00:00'}, {'dt': 1750636800, 'main': {'temp': 289.21, 'feels_like': 288.86, 'temp_min': 289.21, 'temp_max': 289.21, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1007, 'humidity': 76, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 65}, 'wind': {'speed': 5.69, 'deg': 232, 'gust': 12.23}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-06-23 00:00:00'}, {'dt': 1750647600, 'main': {'temp': 289.05, 'feels_like': 288.81, 'temp_min': 289.05, 'temp_max': 289.05, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1007, 'humidity': 81, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 69}, 'wind': {'speed': 5.9, 'deg': 260, 'gust': 12.07}, 'visibility': 10000, 'pop': 0.2, 'rain': {'3h': 0.23}, 'sys': {'pod': 'n'}, 'dt_txt': '2025-06-23 03:00:00'}, {'dt': 1750658400, 'main': {'temp': 288.5, 'feels_like': 287.66, 'temp_min': 288.5, 'temp_max': 288.5, 'pressure': 1013, 'sea_level': 1013, 'grnd_level': 1009, 'humidity': 60, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 68}, 'wind': {'speed': 5.84, 'deg': 287, 'gust': 10.45}, 'visibility': 10000, 'pop': 0.2, 'rain': {'3h': 0.22}, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-23 06:00:00'}, {'dt': 1750669200, 'main': {'temp': 290.57, 'feels_like': 289.57, 'temp_min': 290.57, 'temp_max': 290.57, 'pressure': 1014, 'sea_level': 1014, 'grnd_level': 1010, 'humidity': 46, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 34}, 'wind': {'speed': 5.86, 'deg': 281, 'gust': 8.63}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-23 09:00:00'}, {'dt': 1750680000, 'main': {'temp': 294.56, 'feels_like': 293.59, 'temp_min': 294.56, 'temp_max': 294.56, 'pressure': 1015, 'sea_level': 1015, 'grnd_level': 1010, 'humidity': 32, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 44}, 'wind': {'speed': 5.44, 'deg': 282, 'gust': 8.25}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-23 12:00:00'}, {'dt': 1750690800, 'main': {'temp': 296.24, 'feels_like': 295.41, 'temp_min': 296.24, 'temp_max': 296.24, 'pressure': 1014, 'sea_level': 1014, 'grnd_level': 1010, 'humidity': 31, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 11}, 'wind': {'speed': 6.68, 'deg': 273, 'gust': 9.1}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-23 15:00:00'}, {'dt': 1750701600, 'main': {'temp': 293.92, 'feels_like': 293.12, 'temp_min': 293.92, 'temp_max': 293.92, 'pressure': 1015, 'sea_level': 1015, 'grnd_level': 1011, 'humidity': 41, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 10}, 'wind': {'speed': 6.26, 'deg': 265, 'gust': 7.92}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-23 18:00:00'}, {'dt': 1750712400, 'main': {'temp': 290.16, 'feels_like': 289.3, 'temp_min': 290.16, 'temp_max': 290.16, 'pressure': 1016, 'sea_level': 1016, 'grnd_level': 1011, 'humidity': 53, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03n'}], 'clouds': {'all': 32}, 'wind': {'speed': 4.7, 'deg': 261, 'gust': 8.39}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-06-23 21:00:00'}, {'dt': 1750723200, 'main': {'temp': 287.63, 'feels_like': 286.94, 'temp_min': 287.63, 'temp_max': 287.63, 'pressure': 1015, 'sea_level': 1015, 'grnd_level': 1011, 'humidity': 69, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03n'}], 'clouds': {'all': 37}, 'wind': {'speed': 3.98, 'deg': 250, 'gust': 10.08}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-06-24 00:00:00'}, {'dt': 1750734000, 'main': {'temp': 286.8, 'feels_like': 286.23, 'temp_min': 286.8, 'temp_max': 286.8, 'pressure': 1014, 'sea_level': 1014, 'grnd_level': 1010, 'humidity': 77, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03n'}], 'clouds': {'all': 45}, 'wind': {'speed': 4.3, 'deg': 234, 'gust': 11.54}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-06-24 03:00:00'}, {'dt': 1750744800, 'main': {'temp': 289.18, 'feels_like': 288.8, 'temp_min': 289.18, 'temp_max': 289.18, 'pressure': 1013, 'sea_level': 1013, 'grnd_level': 1009, 'humidity': 75, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 61}, 'wind': {'speed': 5.12, 'deg': 231, 'gust': 12.28}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-24 06:00:00'}, {'dt': 1750755600, 'main': {'temp': 292.25, 'feels_like': 292.02, 'temp_min': 292.25, 'temp_max': 292.25, 'pressure': 1013, 'sea_level': 1013, 'grnd_level': 1009, 'humidity': 69, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 5.86, 'deg': 241, 'gust': 9.61}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-24 09:00:00'}, {'dt': 1750766400, 'main': {'temp': 296.96, 'feels_like': 296.88, 'temp_min': 296.96, 'temp_max': 296.96, 'pressure': 1013, 'sea_level': 1013, 'grnd_level': 1008, 'humidity': 57, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 6.5, 'deg': 252, 'gust': 10.62}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-24 12:00:00'}, {'dt': 1750777200, 'main': {'temp': 298.66, 'feels_like': 298.55, 'temp_min': 298.66, 'temp_max': 298.66, 'pressure': 1012, 'sea_level': 1012, 'grnd_level': 1008, 'humidity': 49, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 50}, 'wind': {'speed': 7.05, 'deg': 240, 'gust': 11.94}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-24 15:00:00'}, {'dt': 1750788000, 'main': {'temp': 298.42, 'feels_like': 298.33, 'temp_min': 298.42, 'temp_max': 298.42, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1007, 'humidity': 51, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 47}, 'wind': {'speed': 5.84, 'deg': 256, 'gust': 10.59}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-24 18:00:00'}, {'dt': 1750798800, 'main': {'temp': 293.79, 'feels_like': 293.76, 'temp_min': 293.79, 'temp_max': 293.79, 'pressure': 1013, 'sea_level': 1013, 'grnd_level': 1009, 'humidity': 71, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02n'}], 'clouds': {'all': 14}, 'wind': {'speed': 4.03, 'deg': 269, 'gust': 9.56}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-06-24 21:00:00'}, {'dt': 1750809600, 'main': {'temp': 290.83, 'feels_like': 290.61, 'temp_min': 290.83, 'temp_max': 290.83, 'pressure': 1013, 'sea_level': 1013, 'grnd_level': 1009, 'humidity': 75, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 8}, 'wind': {'speed': 3.25, 'deg': 255, 'gust': 9.27}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-06-25 00:00:00'}, {'dt': 1750820400, 'main': {'temp': 289.2, 'feels_like': 289.11, 'temp_min': 289.2, 'temp_max': 289.2, 'pressure': 1013, 'sea_level': 1013, 'grnd_level': 1009, 'humidity': 86, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 7}, 'wind': {'speed': 2.45, 'deg': 263, 'gust': 8.07}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-06-25 03:00:00'}, {'dt': 1750831200, 'main': {'temp': 290.08, 'feels_like': 289.73, 'temp_min': 290.08, 'temp_max': 290.08, 'pressure': 1012, 'sea_level': 1012, 'grnd_level': 1008, 'humidity': 73, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 20}, 'wind': {'speed': 2.84, 'deg': 286, 'gust': 5.05}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-25 06:00:00'}, {'dt': 1750842000, 'main': {'temp': 295.46, 'feels_like': 294.95, 'temp_min': 295.46, 'temp_max': 295.46, 'pressure': 1012, 'sea_level': 1012, 'grnd_level': 1008, 'humidity': 46, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 65}, 'wind': {'speed': 2.38, 'deg': 250, 'gust': 3.76}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-25 09:00:00'}, {'dt': 1750852800, 'main': {'temp': 299.72, 'feels_like': 299.72, 'temp_min': 299.72, 'temp_max': 299.72, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1007, 'humidity': 42, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 68}, 'wind': {'speed': 3.67, 'deg': 202, 'gust': 5.43}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-25 12:00:00'}, {'dt': 1750863600, 'main': {'temp': 299.78, 'feels_like': 299.78, 'temp_min': 299.78, 'temp_max': 299.78, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 1005, 'humidity': 41, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 4, 'deg': 214, 'gust': 5.68}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-25 15:00:00'}, {'dt': 1750874400, 'main': {'temp': 297.92, 'feels_like': 297.68, 'temp_min': 297.92, 'temp_max': 297.92, 'pressure': 1008, 'sea_level': 1008, 'grnd_level': 1004, 'humidity': 47, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 85}, 'wind': {'speed': 4.18, 'deg': 262, 'gust': 4.78}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-25 18:00:00'}, {'dt': 1750885200, 'main': {'temp': 293.92, 'feels_like': 293.72, 'temp_min': 293.92, 'temp_max': 293.92, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 1003, 'humidity': 64, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 51}, 'wind': {'speed': 2.59, 'deg': 263, 'gust': 5.81}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-06-25 21:00:00'}, {'dt': 1750896000, 'main': {'temp': 290.86, 'feels_like': 291.06, 'temp_min': 290.86, 'temp_max': 290.86, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 1003, 'humidity': 91, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 76}, 'wind': {'speed': 2.58, 'deg': 251, 'gust': 6.64}, 'visibility': 10000, 'pop': 0.99, 'rain': {'3h': 0.96}, 'sys': {'pod': 'n'}, 'dt_txt': '2025-06-26 00:00:00'}, {'dt': 1750906800, 'main': {'temp': 289.85, 'feels_like': 290.03, 'temp_min': 289.85, 'temp_max': 289.85, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 1002, 'humidity': 94, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 100}, 'wind': {'speed': 3.2, 'deg': 231, 'gust': 8.37}, 'visibility': 10000, 'pop': 0.64, 'rain': {'3h': 0.3}, 'sys': {'pod': 'n'}, 'dt_txt': '2025-06-26 03:00:00'}, {'dt': 1750917600, 'main': {'temp': 289.94, 'feels_like': 290.16, 'temp_min': 289.94, 'temp_max': 289.94, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 1003, 'humidity': 95, 'temp_kf': 0}, 'weather': [{'id': 501, 'main': 'Rain', 'description': 'moderate rain', 'icon': '10d'}], 'clouds': {'all': 100}, 'wind': {'speed': 5.56, 'deg': 238, 'gust': 11.18}, 'visibility': 10000, 'pop': 1, 'rain': {'3h': 3.16}, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-26 06:00:00'}, {'dt': 1750928400, 'main': {'temp': 292.39, 'feels_like': 291.91, 'temp_min': 292.39, 'temp_max': 292.39, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1006, 'humidity': 59, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 67}, 'wind': {'speed': 5.72, 'deg': 279, 'gust': 8.51}, 'visibility': 10000, 'pop': 0.31, 'rain': {'3h': 0.25}, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-26 09:00:00'}, {'dt': 1750939200, 'main': {'temp': 296.73, 'feels_like': 296.01, 'temp_min': 296.73, 'temp_max': 296.73, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1007, 'humidity': 33, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 41}, 'wind': {'speed': 5.3, 'deg': 274, 'gust': 8.33}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-26 12:00:00'}, {'dt': 1750950000, 'main': {'temp': 296.8, 'feels_like': 296.03, 'temp_min': 296.8, 'temp_max': 296.8, 'pressure': 1013, 'sea_level': 1013, 'grnd_level': 1009, 'humidity': 31, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 69}, 'wind': {'speed': 7.02, 'deg': 265, 'gust': 8.78}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-26 15:00:00'}, {'dt': 1750960800, 'main': {'temp': 293.64, 'feels_like': 292.84, 'temp_min': 293.64, 'temp_max': 293.64, 'pressure': 1015, 'sea_level': 1015, 'grnd_level': 1011, 'humidity': 42, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 83}, 'wind': {'speed': 6.2, 'deg': 267, 'gust': 8.8}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-26 18:00:00'}, {'dt': 1750971600, 'main': {'temp': 290.17, 'feels_like': 289.26, 'temp_min': 290.17, 'temp_max': 290.17, 'pressure': 1018, 'sea_level': 1018, 'grnd_level': 1014, 'humidity': 51, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 58}, 'wind': {'speed': 4.41, 'deg': 269, 'gust': 8.11}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-06-26 21:00:00'}, {'dt': 1750982400, 'main': {'temp': 288.1, 'feels_like': 287.32, 'temp_min': 288.1, 'temp_max': 288.1, 'pressure': 1019, 'sea_level': 1019, 'grnd_level': 1015, 'humidity': 64, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03n'}], 'clouds': {'all': 35}, 'wind': {'speed': 3.39, 'deg': 264, 'gust': 8.71}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-06-27 00:00:00'}, {'dt': 1750993200, 'main': {'temp': 287.13, 'feels_like': 286.41, 'temp_min': 287.13, 'temp_max': 287.13, 'pressure': 1020, 'sea_level': 1020, 'grnd_level': 1015, 'humidity': 70, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03n'}], 'clouds': {'all': 34}, 'wind': {'speed': 3.02, 'deg': 246, 'gust': 7.99}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-06-27 03:00:00'}, {'dt': 1751004000, 'main': {'temp': 288.37, 'feels_like': 287.67, 'temp_min': 288.37, 'temp_max': 288.37, 'pressure': 1021, 'sea_level': 1021, 'grnd_level': 1016, 'humidity': 66, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 24}, 'wind': {'speed': 3.55, 'deg': 233, 'gust': 7.01}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-27 06:00:00'}], 'city': {'id': 2643743, 'name': 'London', 'coord': {'lat': 51.5085, 'lon': -0.1257}, 'country': 'GB', 'population': 1000000, 'timezone': 3600, 'sunrise': 1750563800, 'sunset': 1750623697}}

In [53]:
def parse_list(response):
    for item in response['list']:
        print(item)
parse_list(data) #PRINTS ALL CONTENT IN LIST SECTION

{'dt': 1750582800, 'main': {'temp': 294.01, 'feels_like': 293.9, 'temp_min': 293.98, 'temp_max': 294.01, 'pressure': 1014, 'sea_level': 1014, 'grnd_level': 1010, 'humidity': 67, 'temp_kf': 0.03}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 13}, 'wind': {'speed': 5.67, 'deg': 248, 'gust': 8.67}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-22 09:00:00'}
{'dt': 1750593600, 'main': {'temp': 294.92, 'feels_like': 294.67, 'temp_min': 294.92, 'temp_max': 296.75, 'pressure': 1014, 'sea_level': 1014, 'grnd_level': 1009, 'humidity': 58, 'temp_kf': -1.83}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 16}, 'wind': {'speed': 6.79, 'deg': 239, 'gust': 10.62}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-22 12:00:00'}
{'dt': 1750604400, 'main': {'temp': 293.78, 'feels_like': 293.23, 'temp_min': 293.66, 'temp_max': 293.78, 'pressure': 1013, 'sea_level': 1013, 'grnd_level': 1008, 'humidity': 51, 'temp_kf': 0.12}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 71}, 'wind': {'speed': 7.54, 'deg': 229, 'gust': 11.01}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-22 15:00:00'}
{'dt': 1750615200, 'main': {'temp': 294.06, 'feels_like': 293.67, 'temp_min': 294.06, 'temp_max': 294.06, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1007, 'humidity': 56, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 5.79, 'deg': 251, 'gust': 10.58}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-22 18:00:00'}
{'dt': 1750626000, 'main': {'temp': 289.43, 'feels_like': 288.78, 'temp_min': 289.43, 'temp_max': 289.43, 'pressure': 1012, 'sea_level': 1012, 'grnd_level': 1008, 'humidity': 64, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 72}, 'wind': {'speed': 4.59, 'deg': 255, 'gust': 11.44}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-06-22 21:00:00'}
{'dt': 1750636800, 'main': {'temp': 289.21, 'feels_like': 288.86, 'temp_min': 289.21, 'temp_max': 289.21, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1007, 'humidity': 76, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 65}, 'wind': {'speed': 5.69, 'deg': 232, 'gust': 12.23}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-06-23 00:00:00'}
{'dt': 1750647600, 'main': {'temp': 289.05, 'feels_like': 288.81, 'temp_min': 289.05, 'temp_max': 289.05, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1007, 'humidity': 81, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 69}, 'wind': {'speed': 5.9, 'deg': 260, 'gust': 12.07}, 'visibility': 10000, 'pop': 0.2, 'rain': {'3h': 0.23}, 'sys': {'pod': 'n'}, 'dt_txt': '2025-06-23 03:00:00'}
{'dt': 1750658400, 'main': {'temp': 288.5, 'feels_like': 287.66, 'temp_min': 288.5, 'temp_max': 288.5, 'pressure': 1013, 'sea_level': 1013, 'grnd_level': 1009, 'humidity': 60, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 68}, 'wind': {'speed': 5.84, 'deg': 287, 'gust': 10.45}, 'visibility': 10000, 'pop': 0.2, 'rain': {'3h': 0.22}, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-23 06:00:00'}
{'dt': 1750669200, 'main': {'temp': 290.57, 'feels_like': 289.57, 'temp_min': 290.57, 'temp_max': 290.57, 'pressure': 1014, 'sea_level': 1014, 'grnd_level': 1010, 'humidity': 46, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 34}, 'wind': {'speed': 5.86, 'deg': 281, 'gust': 8.63}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-23 09:00:00'}
{'dt': 1750680000, 'main': {'temp': 294.56, 'feels_like': 293.59, 'temp_min': 294.56, 'temp_max': 294.56, 'pressure': 1015, 'sea_level': 1015, 'grnd_level': 1010, 'humidity': 32, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 44}, 'wind': {'speed': 5.44, 'deg': 282, 'gust': 8.25}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-23 12:00:00'}
{'dt': 1750690800, 'main': {'temp': 296.24, 'feels_like': 295.41, 'temp_min': 296.24, 'temp_max': 296.24, 'pressure': 1014, 'sea_level': 1014, 'grnd_level': 1010, 'humidity': 31, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 11}, 'wind': {'speed': 6.68, 'deg': 273, 'gust': 9.1}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-23 15:00:00'}
{'dt': 1750701600, 'main': {'temp': 293.92, 'feels_like': 293.12, 'temp_min': 293.92, 'temp_max': 293.92, 'pressure': 1015, 'sea_level': 1015, 'grnd_level': 1011, 'humidity': 41, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 10}, 'wind': {'speed': 6.26, 'deg': 265, 'gust': 7.92}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-23 18:00:00'}
{'dt': 1750712400, 'main': {'temp': 290.16, 'feels_like': 289.3, 'temp_min': 290.16, 'temp_max': 290.16, 'pressure': 1016, 'sea_level': 1016, 'grnd_level': 1011, 'humidity': 53, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03n'}], 'clouds': {'all': 32}, 'wind': {'speed': 4.7, 'deg': 261, 'gust': 8.39}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-06-23 21:00:00'}
{'dt': 1750723200, 'main': {'temp': 287.63, 'feels_like': 286.94, 'temp_min': 287.63, 'temp_max': 287.63, 'pressure': 1015, 'sea_level': 1015, 'grnd_level': 1011, 'humidity': 69, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03n'}], 'clouds': {'all': 37}, 'wind': {'speed': 3.98, 'deg': 250, 'gust': 10.08}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-06-24 00:00:00'}
{'dt': 1750734000, 'main': {'temp': 286.8, 'feels_like': 286.23, 'temp_min': 286.8, 'temp_max': 286.8, 'pressure': 1014, 'sea_level': 1014, 'grnd_level': 1010, 'humidity': 77, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03n'}], 'clouds': {'all': 45}, 'wind': {'speed': 4.3, 'deg': 234, 'gust': 11.54}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-06-24 03:00:00'}
{'dt': 1750744800, 'main': {'temp': 289.18, 'feels_like': 288.8, 'temp_min': 289.18, 'temp_max': 289.18, 'pressure': 1013, 'sea_level': 1013, 'grnd_level': 1009, 'humidity': 75, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 61}, 'wind': {'speed': 5.12, 'deg': 231, 'gust': 12.28}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-24 06:00:00'}
{'dt': 1750755600, 'main': {'temp': 292.25, 'feels_like': 292.02, 'temp_min': 292.25, 'temp_max': 292.25, 'pressure': 1013, 'sea_level': 1013, 'grnd_level': 1009, 'humidity': 69, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 5.86, 'deg': 241, 'gust': 9.61}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-24 09:00:00'}
{'dt': 1750766400, 'main': {'temp': 296.96, 'feels_like': 296.88, 'temp_min': 296.96, 'temp_max': 296.96, 'pressure': 1013, 'sea_level': 1013, 'grnd_level': 1008, 'humidity': 57, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 6.5, 'deg': 252, 'gust': 10.62}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-24 12:00:00'}
{'dt': 1750777200, 'main': {'temp': 298.66, 'feels_like': 298.55, 'temp_min': 298.66, 'temp_max': 298.66, 'pressure': 1012, 'sea_level': 1012, 'grnd_level': 1008, 'humidity': 49, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 50}, 'wind': {'speed': 7.05, 'deg': 240, 'gust': 11.94}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-24 15:00:00'}
{'dt': 1750788000, 'main': {'temp': 298.42, 'feels_like': 298.33, 'temp_min': 298.42, 'temp_max': 298.42, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1007, 'humidity': 51, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 47}, 'wind': {'speed': 5.84, 'deg': 256, 'gust': 10.59}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-24 18:00:00'}
{'dt': 1750798800, 'main': {'temp': 293.79, 'feels_like': 293.76, 'temp_min': 293.79, 'temp_max': 293.79, 'pressure': 1013, 'sea_level': 1013, 'grnd_level': 1009, 'humidity': 71, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02n'}], 'clouds': {'all': 14}, 'wind': {'speed': 4.03, 'deg': 269, 'gust': 9.56}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-06-24 21:00:00'}
{'dt': 1750809600, 'main': {'temp': 290.83, 'feels_like': 290.61, 'temp_min': 290.83, 'temp_max': 290.83, 'pressure': 1013, 'sea_level': 1013, 'grnd_level': 1009, 'humidity': 75, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 8}, 'wind': {'speed': 3.25, 'deg': 255, 'gust': 9.27}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-06-25 00:00:00'}
{'dt': 1750820400, 'main': {'temp': 289.2, 'feels_like': 289.11, 'temp_min': 289.2, 'temp_max': 289.2, 'pressure': 1013, 'sea_level': 1013, 'grnd_level': 1009, 'humidity': 86, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 7}, 'wind': {'speed': 2.45, 'deg': 263, 'gust': 8.07}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-06-25 03:00:00'}
{'dt': 1750831200, 'main': {'temp': 290.08, 'feels_like': 289.73, 'temp_min': 290.08, 'temp_max': 290.08, 'pressure': 1012, 'sea_level': 1012, 'grnd_level': 1008, 'humidity': 73, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 20}, 'wind': {'speed': 2.84, 'deg': 286, 'gust': 5.05}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-25 06:00:00'}
{'dt': 1750842000, 'main': {'temp': 295.46, 'feels_like': 294.95, 'temp_min': 295.46, 'temp_max': 295.46, 'pressure': 1012, 'sea_level': 1012, 'grnd_level': 1008, 'humidity': 46, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 65}, 'wind': {'speed': 2.38, 'deg': 250, 'gust': 3.76}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-25 09:00:00'}
{'dt': 1750852800, 'main': {'temp': 299.72, 'feels_like': 299.72, 'temp_min': 299.72, 'temp_max': 299.72, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1007, 'humidity': 42, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 68}, 'wind': {'speed': 3.67, 'deg': 202, 'gust': 5.43}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-25 12:00:00'}
{'dt': 1750863600, 'main': {'temp': 299.78, 'feels_like': 299.78, 'temp_min': 299.78, 'temp_max': 299.78, 'pressure': 1009, 'sea_level': 1009, 'grnd_level': 1005, 'humidity': 41, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 4, 'deg': 214, 'gust': 5.68}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-25 15:00:00'}
{'dt': 1750874400, 'main': {'temp': 297.92, 'feels_like': 297.68, 'temp_min': 297.92, 'temp_max': 297.92, 'pressure': 1008, 'sea_level': 1008, 'grnd_level': 1004, 'humidity': 47, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 85}, 'wind': {'speed': 4.18, 'deg': 262, 'gust': 4.78}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-25 18:00:00'}
{'dt': 1750885200, 'main': {'temp': 293.92, 'feels_like': 293.72, 'temp_min': 293.92, 'temp_max': 293.92, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 1003, 'humidity': 64, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 51}, 'wind': {'speed': 2.59, 'deg': 263, 'gust': 5.81}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-06-25 21:00:00'}
{'dt': 1750896000, 'main': {'temp': 290.86, 'feels_like': 291.06, 'temp_min': 290.86, 'temp_max': 290.86, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 1003, 'humidity': 91, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 76}, 'wind': {'speed': 2.58, 'deg': 251, 'gust': 6.64}, 'visibility': 10000, 'pop': 0.99, 'rain': {'3h': 0.96}, 'sys': {'pod': 'n'}, 'dt_txt': '2025-06-26 00:00:00'}
{'dt': 1750906800, 'main': {'temp': 289.85, 'feels_like': 290.03, 'temp_min': 289.85, 'temp_max': 289.85, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 1002, 'humidity': 94, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 100}, 'wind': {'speed': 3.2, 'deg': 231, 'gust': 8.37}, 'visibility': 10000, 'pop': 0.64, 'rain': {'3h': 0.3}, 'sys': {'pod': 'n'}, 'dt_txt': '2025-06-26 03:00:00'}
{'dt': 1750917600, 'main': {'temp': 289.94, 'feels_like': 290.16, 'temp_min': 289.94, 'temp_max': 289.94, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 1003, 'humidity': 95, 'temp_kf': 0}, 'weather': [{'id': 501, 'main': 'Rain', 'description': 'moderate rain', 'icon': '10d'}], 'clouds': {'all': 100}, 'wind': {'speed': 5.56, 'deg': 238, 'gust': 11.18}, 'visibility': 10000, 'pop': 1, 'rain': {'3h': 3.16}, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-26 06:00:00'}
{'dt': 1750928400, 'main': {'temp': 292.39, 'feels_like': 291.91, 'temp_min': 292.39, 'temp_max': 292.39, 'pressure': 1010, 'sea_level': 1010, 'grnd_level': 1006, 'humidity': 59, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10d'}], 'clouds': {'all': 67}, 'wind': {'speed': 5.72, 'deg': 279, 'gust': 8.51}, 'visibility': 10000, 'pop': 0.31, 'rain': {'3h': 0.25}, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-26 09:00:00'}
{'dt': 1750939200, 'main': {'temp': 296.73, 'feels_like': 296.01, 'temp_min': 296.73, 'temp_max': 296.73, 'pressure': 1011, 'sea_level': 1011, 'grnd_level': 1007, 'humidity': 33, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 41}, 'wind': {'speed': 5.3, 'deg': 274, 'gust': 8.33}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-26 12:00:00'}
{'dt': 1750950000, 'main': {'temp': 296.8, 'feels_like': 296.03, 'temp_min': 296.8, 'temp_max': 296.8, 'pressure': 1013, 'sea_level': 1013, 'grnd_level': 1009, 'humidity': 31, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 69}, 'wind': {'speed': 7.02, 'deg': 265, 'gust': 8.78}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-26 15:00:00'}
{'dt': 1750960800, 'main': {'temp': 293.64, 'feels_like': 292.84, 'temp_min': 293.64, 'temp_max': 293.64, 'pressure': 1015, 'sea_level': 1015, 'grnd_level': 1011, 'humidity': 42, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 83}, 'wind': {'speed': 6.2, 'deg': 267, 'gust': 8.8}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-26 18:00:00'}
{'dt': 1750971600, 'main': {'temp': 290.17, 'feels_like': 289.26, 'temp_min': 290.17, 'temp_max': 290.17, 'pressure': 1018, 'sea_level': 1018, 'grnd_level': 1014, 'humidity': 51, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 58}, 'wind': {'speed': 4.41, 'deg': 269, 'gust': 8.11}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-06-26 21:00:00'}
{'dt': 1750982400, 'main': {'temp': 288.1, 'feels_like': 287.32, 'temp_min': 288.1, 'temp_max': 288.1, 'pressure': 1019, 'sea_level': 1019, 'grnd_level': 1015, 'humidity': 64, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03n'}], 'clouds': {'all': 35}, 'wind': {'speed': 3.39, 'deg': 264, 'gust': 8.71}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-06-27 00:00:00'}
{'dt': 1750993200, 'main': {'temp': 287.13, 'feels_like': 286.41, 'temp_min': 287.13, 'temp_max': 287.13, 'pressure': 1020, 'sea_level': 1020, 'grnd_level': 1015, 'humidity': 70, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03n'}], 'clouds': {'all': 34}, 'wind': {'speed': 3.02, 'deg': 246, 'gust': 7.99}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2025-06-27 03:00:00'}
{'dt': 1751004000, 'main': {'temp': 288.37, 'feels_like': 287.67, 'temp_min': 288.37, 'temp_max': 288.37, 'pressure': 1021, 'sea_level': 1021, 'grnd_level': 1016, 'humidity': 66, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 24}, 'wind': {'speed': 3.55, 'deg': 233, 'gust': 7.01}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2025-06-27 06:00:00'}

EXTRACT REQUIREMENTS TO DATAFRAME(CSV)

In [54]:
def parse_list(response):
    charlist = []
    for item in response['list']:
        dt = item['dt_txt']
        temp = item['main']['temp']
        weather_info={
            "weather":item['weather'][0]['main'],
            "description":item['weather'][0]['description']
        }
        conv_temp=temp-273.15
        print(f"{dt}: {temp}K",{weather_info['weather']},{weather_info['description']})

        
        
        char = {
            "datetime": dt,
            "temperature": temp,
           "weather_info":json.dumps(weather_info),
            "conv_temp":round(conv_temp,2)
        }
        charlist.append(char)
    return charlist

parsed_data = (parse_list(data))

2025-06-22 09:00:00: 294.01K {'Clouds'} {'few clouds'}
2025-06-22 12:00:00: 294.92K {'Clouds'} {'few clouds'}
2025-06-22 15:00:00: 293.78K {'Clouds'} {'broken clouds'}
2025-06-22 18:00:00: 294.06K {'Clouds'} {'overcast clouds'}
2025-06-22 21:00:00: 289.43K {'Clouds'} {'broken clouds'}
2025-06-23 00:00:00: 289.21K {'Clouds'} {'broken clouds'}
2025-06-23 03:00:00: 289.05K {'Rain'} {'light rain'}
2025-06-23 06:00:00: 288.5K {'Rain'} {'light rain'}
2025-06-23 09:00:00: 290.57K {'Clouds'} {'scattered clouds'}
2025-06-23 12:00:00: 294.56K {'Clouds'} {'scattered clouds'}
2025-06-23 15:00:00: 296.24K {'Clouds'} {'few clouds'}
2025-06-23 18:00:00: 293.92K {'Clear'} {'clear sky'}
2025-06-23 21:00:00: 290.16K {'Clouds'} {'scattered clouds'}
2025-06-24 00:00:00: 287.63K {'Clouds'} {'scattered clouds'}
2025-06-24 03:00:00: 286.8K {'Clouds'} {'scattered clouds'}
2025-06-24 06:00:00: 289.18K {'Clouds'} {'broken clouds'}
2025-06-24 09:00:00: 292.25K {'Clouds'} {'overcast clouds'}
2025-06-24 12:00:00: 296.96K {'Clouds'} {'overcast clouds'}
2025-06-24 15:00:00: 298.66K {'Clouds'} {'scattered clouds'}
2025-06-24 18:00:00: 298.42K {'Clouds'} {'scattered clouds'}
2025-06-24 21:00:00: 293.79K {'Clouds'} {'few clouds'}
2025-06-25 00:00:00: 290.83K {'Clear'} {'clear sky'}
2025-06-25 03:00:00: 289.2K {'Clear'} {'clear sky'}
2025-06-25 06:00:00: 290.08K {'Clouds'} {'few clouds'}
2025-06-25 09:00:00: 295.46K {'Clouds'} {'broken clouds'}
2025-06-25 12:00:00: 299.72K {'Clouds'} {'broken clouds'}
2025-06-25 15:00:00: 299.78K {'Clouds'} {'overcast clouds'}
2025-06-25 18:00:00: 297.92K {'Clouds'} {'overcast clouds'}
2025-06-25 21:00:00: 293.92K {'Clouds'} {'broken clouds'}
2025-06-26 00:00:00: 290.86K {'Rain'} {'light rain'}
2025-06-26 03:00:00: 289.85K {'Rain'} {'light rain'}
2025-06-26 06:00:00: 289.94K {'Rain'} {'moderate rain'}
2025-06-26 09:00:00: 292.39K {'Rain'} {'light rain'}
2025-06-26 12:00:00: 296.73K {'Clouds'} {'scattered clouds'}
2025-06-26 15:00:00: 296.8K {'Clouds'} {'broken clouds'}
2025-06-26 18:00:00: 293.64K {'Clouds'} {'broken clouds'}
2025-06-26 21:00:00: 290.17K {'Clouds'} {'broken clouds'}
2025-06-27 00:00:00: 288.1K {'Clouds'} {'scattered clouds'}
2025-06-27 03:00:00: 287.13K {'Clouds'} {'scattered clouds'}
2025-06-27 06:00:00: 288.37K {'Clouds'} {'few clouds'}

In [55]:
import pandas as pd
from datetime import datetime
weather_df = pd.DataFrame(parsed_data)


now=datetime.utcnow()
weather_df['valid_from']=now
#raw_df['valid_to']=pd.NaT
#raw_df['is_current']= True

/var/folders/pb/q49x3lbx6313whr2jx93rk180000gn/T/ipykernel_73569/2173709070.py:6: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  now=datetime.utcnow()

In [56]:
print(f"DataFrame columns: {list(weather_df.columns)}")

DataFrame columns: ['datetime', 'temperature', 'weather_info', 'conv_temp', 'valid_from']

In [57]:
print(weather_df.columns.tolist())

['datetime', 'temperature', 'weather_info', 'conv_temp', 'valid_from']

In [58]:
# Check the data type
print(f"weather_info dtype: {weather_df['weather_info'].dtype}")
print(f"Sample value: {weather_df['weather_info'].iloc[0]}")

weather_info dtype: object
Sample value: {"weather": "Clouds", "description": "few clouds"}

In [59]:
weather_df.head()

,datetime,temperature,weather_info,conv_temp,valid_from
0,2025-06-22 09:00:00,294.01,"{""weather"": ""Clouds"", ""description"": ""few clou...",20.86,2025-06-22 08:12:51.926183
1,2025-06-22 12:00:00,294.92,"{""weather"": ""Clouds"", ""description"": ""few clou...",21.77,2025-06-22 08:12:51.926183
2,2025-06-22 15:00:00,293.78,"{""weather"": ""Clouds"", ""description"": ""broken c...",20.63,2025-06-22 08:12:51.926183
3,2025-06-22 18:00:00,294.06,"{""weather"": ""Clouds"", ""description"": ""overcast...",20.91,2025-06-22 08:12:51.926183
4,2025-06-22 21:00:00,289.43,"{""weather"": ""Clouds"", ""description"": ""broken c...",16.28,2025-06-22 08:12:51.926183

In [60]:
# Save to CSV
weather_df.to_csv('weather_forecast_json.csv', index=False)

print("CSV file saved as weather_forecast_json.csv")

CSV file saved as weather_forecast_json.csv

In [61]:
import os
# Define your file path (choose ONE approach)
file_path = "/Users/apple/Desktop/DATA ENG/APIs/weather_forecast_json.csv"  # Fixed the apostrophe
# OR use current directory: file_path = "weather_forecast.csv"

# Create directory if it doesn't exist
#os.makedirs(os.path.dirname(file_path), exist_ok=True)

# Load existing data if file exists
if os.path.exists(file_path):
    print("Loading existing data...")
    df_existing = pd.read_csv(file_path)
    print(f"Existing data shape: {df_existing.shape}")
    
else:
    print("No existing file found, using new data only...")

Loading existing data...
Existing data shape: (40, 5)

In [62]:
import psycopg2 #for connecting to PostgreSQL database and executing queries
from sqlalchemy import create_engine #To efficiently manage and reuse datavase connections
password='bens'

db_username='postgres'
db_password=password
db_host='localhost'
db_port=5432
db_name='ben'

In [63]:
# Overwrite existing records
#raw_df.to_sql('weather_data_json', engine, if_exists='replace', index=False)

In [64]:
from sqlalchemy import create_engine, text
import pandas as pd
from sqlalchemy.dialects.postgresql import JSONB

# Database credentials
db_username = 'postgres'
db_password = 'bens'
db_host = 'localhost'
db_port = '5432'
db_name = 'ben'

# Create engine
engine = create_engine(f'postgresql://{db_username}:{db_password}@{db_host}:{db_port}/{db_name}')

# Create table
with engine.begin() as conn:
    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS weather_data_scd (
            id SERIAL PRIMARY KEY,
            datetime TIMESTAMP,
            temperature DECIMAL(5,2),
            conv_temp DECIMAL(5,2),
            weather_info JSONB NOT NULL,
            valid_from TIMESTAMP DEFAULT NOW(),
            valid_to TIMESTAMP,
            is_current BOOLEAN DEFAULT TRUE,
            UNIQUE(datetime, valid_from)
        );
    """))

def upsert_weather_scd_type2(new_data):
    with engine.begin() as conn:
        # Expire current record if data has changed
        expire_query = text("""
    UPDATE weather_data_scd
    SET valid_to = NOW(), is_current = FALSE
    WHERE datetime = :datetime
      AND is_current = TRUE
      AND (
          temperature != :temperature OR
          conv_temp != :conv_temp OR
          weather_info != :weather_info
      );
""")

        conn.execute(expire_query, new_data)

        # Insert new current record if not already there
        insert_query = text("""
    INSERT INTO weather_data_scd (
        datetime, temperature, conv_temp, weather_info,
        valid_from, valid_to, is_current
    )
    SELECT 
        :datetime, :temperature, :conv_temp, :weather_info,
        NOW(), NULL, TRUE
    WHERE NOT EXISTS (
        SELECT 1 FROM weather_data_scd
        WHERE datetime = :datetime
          AND temperature = :temperature
          AND conv_temp = :conv_temp
          AND weather_info = :weather_info
          AND is_current = TRUE
    );
""")

        conn.execute(insert_query, new_data)

# Example: weather_df must contain 'datetime', 'temperature', 'conv_temp', 'weather_info'
for _, row in weather_df.iterrows():
    new_data = {
        'datetime': row['datetime'],
        'temperature': row['temperature'],
        'conv_temp': row['conv_temp'],
        'weather_info': row['weather_info']  # Should be dict or valid JSON
    }
    upsert_weather_scd_type2(new_data)

In [65]:
from sqlalchemy import text

with engine.connect() as conn:
    result = conn.execute(text("SELECT * FROM weather_data_scd"))
    weather_df = pd.DataFrame(result.fetchall(), columns=result.keys())

weather_df.to_csv("weather_data_scd.csv", index=False)

In [66]:
weather_df[weather_df['is_current'] == True].head()

,id,datetime,temperature,conv_temp,weather_info,valid_from,valid_to,is_current
0,1,2025-06-21 18:00:00,302.26,29.11,"{'weather': 'Clouds', 'description': 'overcast...",2025-06-21 17:47:50.001823,NaT,True
1,2,2025-06-21 21:00:00,298.55,25.40,"{'weather': 'Rain', 'description': 'light rain'}",2025-06-21 17:47:50.039043,NaT,True
2,3,2025-06-22 00:00:00,292.55,19.40,"{'weather': 'Rain', 'description': 'light rain'}",2025-06-21 17:47:50.041963,NaT,True
3,4,2025-06-22 03:00:00,289.01,15.86,"{'weather': 'Clouds', 'description': 'overcast...",2025-06-21 17:47:50.044770,NaT,True
4,5,2025-06-22 06:00:00,290.09,16.94,"{'weather': 'Clouds', 'description': 'overcast...",2025-06-21 17:47:50.048040,NaT,True

In [67]:
# Show all historical records for a specific datetime
historical_query = """
SELECT datetime, temperature, conv_temp, weather_info,
       valid_from, valid_to, is_current
FROM weather_data_scd 
WHERE datetime = '2025-06-22 09:00:00'
ORDER BY valid_from;
"""

with engine.connect() as conn:
    result = conn.execute(text(historical_query))
    historical_df = pd.DataFrame(result.fetchall(), columns=result.keys())
    print(historical_df)

             datetime temperature conv_temp  \
0 2025-06-22 09:00:00      295.90     22.75
1 2025-06-22 09:00:00      292.77     19.62
2 2025-06-22 09:00:00      293.12     19.97
3 2025-06-22 09:00:00      293.22     20.07
4 2025-06-22 09:00:00      293.12     19.97
5 2025-06-22 09:00:00      293.22     20.07
6 2025-06-22 09:00:00      293.97     20.82
7 2025-06-22 09:00:00      294.01     20.86

                                        weather_info  \
0  {'weather': 'Clouds', 'description': 'few clou...
1  {'weather': 'Clouds', 'description': 'broken c...
2  {'weather': 'Clouds', 'description': 'few clou...
3  {'weather': 'Clouds', 'description': 'few clou...
4  {'weather': 'Clouds', 'description': 'few clou...
5  {'weather': 'Clouds', 'description': 'few clou...
6  {'weather': 'Clouds', 'description': 'few clou...
7  {'weather': 'Clouds', 'description': 'few clou...

                  valid_from                   valid_to  is_current
0 2025-06-21 17:47:50.052849 2025-06-22 08:13:29.250014       False
1 2025-06-22 08:13:29.250014 2025-06-22 08:36:28.549502       False
2 2025-06-22 08:36:28.549502 2025-06-22 08:39:02.232116       False
3 2025-06-22 08:39:02.232116 2025-06-22 08:44:12.887187       False
4 2025-06-22 08:44:12.887187 2025-06-22 08:45:31.827321       False
5 2025-06-22 08:45:31.827321 2025-06-22 09:03:43.766743       False
6 2025-06-22 09:03:43.766743 2025-06-22 09:12:52.937399       False
7 2025-06-22 09:12:52.937399                        NaT        True